### ISSUE TITLE
Issue açmayı pek istemedim

### ISSUE THREAD

**Issue by aligoren** [hozakar/basitblog#1]
Büyük teşekkürleri hak ediyorsunuz. Hem hafif hem de kullanışlı. Elinize sağlık üstadım. Kendim yazmaya üşenmiştim. Bir de localde kullanacağız yani düşün. Mükemmel çalışıyor.

**Comment by hozakar** [comment]
Ben teşekkür ederim. Umarım işinize yarar.
8 Tem 2016 17:52 tarihinde "Ali GOREN" notifications@github.com yazdı:
